.vscode

QW
qw-qc

WinQuake/build-native
WinQuake/build-wasm
WinQuake/build-docker
WinQuake/id1/pak0.pak
WinQuake/id1/pak1.pak

.gitignore
build-docker.sh
!build-native.sh
build-wasm.sh
run-docker.sh
run-native.sh
run-wasm.sh

Dockerfile
Dockerfile.dockerignore
