.vscode

QW
qw-qc

WinQuake/emsdk
WinQuake/build-docker/
WinQuake/build-native/
WinQuake/build-wasm
WinQuake/id1/pak0.pak
WinQuake/id1/pak1.pak
WinQuake/id1/qconsole.log
WinQuake/id1/progs/progs.dat
WinQuake/id1/progs/progs.lno
WinQuake/CMakeFiles

.gitignore
build-docker.sh
!build-native.sh
build-wasm.sh
run-docker.sh
run-native.sh
run-wasm.sh

Dockerfile
Dockerfile.dockerignore
